FROM python:3.12-slim

WORKDIR /app

# Fix pkg_resources issue before anything else
RUN pip install --no-cache-dir setuptools==69.0.0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY artifacts/ ./artifacts/

ENV MODEL_URI=models:/rul-predictor/1
ENV MLFLOW_TRACKING_URI=http://mlflow:5000

EXPOSE 8000

CMD ["uvicorn", "src.inference.app:app", "--host", "0.0.0.0", "--port", "8000"]